---
date: "`r paste0('Report Date: ', Sys.Date())`"
output: 
  officedown::rdocx_document:
    reference_docx: template_officedown.docx
---

```{r setup, include=FALSE}
options(knitr.duplicate.label = 'allow')
options(tinytex.verbose = TRUE)

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      error = TRUE,
                      cache = FALSE,
                      cache.comments = FALSE,
                      include = TRUE,
                      autodep = TRUE,
                      eval = TRUE)

library(readxl)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)
library(scales)
library(zoo)
library(knitr)

load("report.RData")

```

---
title: "`r paste0("CyAN Update (2021-04-01 - ", max(dta2$Date), ")")`"
---

<!---BLOCK_LANDSCAPE_START--->

```{r table, echo=FALSE, results = 'asis'}

if(num>10){
  
  knitr::kable(tbl.7dmdm[1:num,], caption = caption_2)
  
} else {
  
  numb <- nrow(tbl.7dmdm[which(!tbl.7dmdm$`7-Day Average Daily Maximum (cells/mL)` == "Non-detect"),])
  
  if(num == numb){
    
    knitr::kable(tbl.7dmdm[1:num,], caption = caption_2)
    
  } else {
    
    knitr::kable(tbl.7dmdm[1:numb,], caption = caption_3)
  }
  
}

```

`r paste0("Figures: Time series plots of daily maximums and daily means of cyanobacteria abundance (cells/mL) of the waterbodies during 2021-04-01 and ", as.Date(max(dta2$Date)), ".")`

```{r ggplot, fig.width=10, fig.height=5, echo=FALSE}

# test: i <- "Odell Lake_01147159"

for(i in gnisidname) {
  
  dta.plot <- dta %>% dplyr::filter(as.Date(Date) >= as.Date("2021-04-01"))
  
  plot <- ggplot(subset(dta.plot, dta.plot$GNISIDNAME == i),
                 aes(x=as.Date(Date), 
                     y=`Cyanobacteria (cells/mL)`,
                     group=`Summary Statistics`,
                     color=`Summary Statistics`)) +
    geom_line(size=1.5) +
    geom_point(color="black", alpha=0.3, size=3) +
    xlab("Date") +
    scale_x_date(date_labels = "%b-%d",
                 date_breaks = "week") +
    ylab("Cyanobacteria (cells/mL)") +
    #scale_y_continuous(labels = comma) +
    scale_y_continuous(trans = log10_trans(),
                       breaks = trans_breaks("log10", function(x) 10^x),
                       labels = trans_format("log10", math_format(10^.x))) +
    geom_hline(yintercept=100000,linetype="dashed",color="red",size=1.5) +
    annotate("text", as.Date(min(dta.plot$Date)), 100000, vjust = 1, hjust = 0,  label = "WHO Guideline") +
    ggtitle(i) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 10),
          axis.text.y = element_text(size = 10),
          axis.title.x = element_text(size = 12),
          axis.title.y = element_text(size = 12),
          plot.title = element_text(size=15))
  
  print(plot)
  
}

```

<!---BLOCK_LANDSCAPE_STOP--->

```{r notuse, echo=FALSE, results = 'asis'}
#knitr::kable(tbl.max.of.daily.mean[1:12,],
#             caption = paste0("Table 1. Waterbodies ranked by the maximum daily mean of cyanobacteria abundance (cells/mL) that are above the WHO guideline (100,000 cells/mL) for cyanobacteria in recreational freshwater during the 7 days from ", as.Date(max(dta2$Date))-7, " to ",max(dta2$Date), ". The basin names and the dates associated with the maximum daily means are shown in the table."))
```